feat: Create the Service Interface and its implementation about the F…
ArianitSGashi/OnlineVotingS pull request #41
Opened 2024-08-19 14:21 UTC by BesmirKrasniqi

…eedback entity

2024-08-19 14:41 UTC, ArianitSGashi approved these changes

2024-08-19 20:07 UTC, AdhurimUP commented on src/OnlineVotingS.Application/Services/IService/IFeedbackService.cs
> +{
do not use '{' on the namespace, beautify with ';'

2024-08-19 20:07 UTC, AdhurimUP commented on src/OnlineVotingS.Application/Services/ImplService/FeedbackService.cs
> +{
do not use '{' on the namespace, beautify with ';'

2024-08-19 20:13 UTC, AdhurimUP commented on src/OnlineVotingS.Application/Services/ImplService/FeedbackService.cs
> +            _mapper.Map(feedbackDto, feedback);
in the future we need to see if the mapping side should be in separated file!

2024-08-19 20:13 UTC, AdhurimUP requested changes
resolve comments!

2024-08-19 20:15 UTC, AdhurimUP commented on src/OnlineVotingS.Application/Services/ImplService/FeedbackService.cs
> +    public class FeedbackService : IFeedbackService
reformat the code in align, remove the typo empty spaces

2024-08-20 08:11 UTC, AdhurimUP approved these changes

2024-08-20 08:11 UTC, merged